version: "3"
services:
  api:
    build: .
    env_file: .env
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
    depends_on:
      - db
  db:
    image: postgres:12
    env_file: .env
    restart: unless-stopped
