version: "3"
services:
  api:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - "./migrations:/app/migrations"
    depends_on:
      - db
  db:
    image: postgres:12
    env_file: .env
